#/usr/bin/ruby
# Generated by Buildr 1.4.4, change to your liking
# Version number for this release
VERSION_NUMBER = "2.0.0"
# Group identifier for your projects
GROUP = "buildr4osgi-bug"
COPYRIGHT = ""

require 'buildr4osgi'

ENV['OSGi'] ||= "#{File.expand_path(Dir.pwd)}/dummyOSGi"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

WithSources = false
desc "The Buildr4osgi-bug project"

define('container') do
  project.group = "grp"
  project.version = '1.0.9'
  
  define("bar", :version => "1.0.0") do
    compile { FileUtils.makedirs _('target/root/resources') }
    package(:bundle)
    package(:sources) if WithSources
  end
 
  define("foo", :version => "1.0.0") do
    f = package(:feature)
    f.plugins << project("container:bar")
    f.label = "My feature"
    f.provider = "Acme Inc"
    f.description = "The best feature ever"
    f.changesURL = "http://example.com/changes"
    f.license = "The license is too long to explain"
    f.licenseURL = "http://example.com/license"
    f.branding_plugin = "com.musal.ui"
    f.update_sites << {:url => "http://example.com/update", :name => "My update site"}
    f.discovery_sites = [{:url => "http://example.com/update2", :name => "My update site2"}, 
      {:url => "http://example.com/upup", :name => "My update site in case"}]
    package(:sources) if WithSources
  end
  
  site = package(:site) do
    category = Buildr4OSGi::Category.new
    category.name = "category.id"
    category.label = "Some Label"
    category.description = "The category is described here"
    category.features<< foo
    site.categories << category
    site    
  end
  package(:p2_from_site) # creates an empty site.xml (70 bytes long)
end
