#!/usr/bin/env ruby
# To test this file you must have an eclipse and fop installed!
# export OSGi=/path/to/eclipse
# buildr osgi:clean:dependencies osgi:resolve:dependencies osgi:install:dependencies
# buildr clean package

require 'buildr4osgi'

Buildr::write "demo/src/main/java/Hello.java", "public class Hello {}"
Buildr::write "demo/readme.textile", IO.readlines('../readme.textile')
Buildr::write "nested/demo2/src/main/java/Hello.java", "public class Hello {}"
Buildr::write "nested/demo2/doc/readme.textile", IO.readlines('../readme.textile')
Buildr::write "nested/demo2/doc/second.textile", IO.readlines('../readme.textile')
desc "An example buildr project which creates a PDF file from an textile markup file"

repositories.remote << "http://repo2.maven.org/maven2"
FOP      = 'org.apache.xmlgraphics:fop:jar:1.0' 
# org.eclipse.mylyn.wikitext cannot be found in a Maven repository
# WIKITEXT = 'org.eclipse.mylyn.wikitext'

def checkPreconditions
  if  Dir.glob("#{ENV['OSGi']}/plugins").size == 0
    puts "Environment variable OSGi must point to a valid eclipse installation"
    exit 1
  end
  if !system('which fop')
    puts "fop must be installed"
    exit 1
  end
end

def genDoku
  Java.load # needed to load class path for apache logger
  pdf2generate = []
  Dir.glob(_('**/*.textile')).each {
    |x|
      dest = "target/#{File.basename(x, '.textile')}.pdf"
      pdf2generate << dest
#      puts "89: Adding #{_(dest)} from #{x}"
      package(:zip).include(_(dest))
  }

  pdf2generate.each { |pdfToGen|
    file pdfToGen do |t|
      Buildr.ant('wikitext_to_xslfo') do |wikitext|
	  wikitext.taskdef :name=>'wikitext_to_xslfo',
	  :classname=>'org.eclipse.mylyn.wikitext.core.util.anttask.MarkupToXslfoTask',
	  :classpath=> Dir.glob("#{ENV['OSGi']}/plugins/org.eclipse.mylyn.wikitext.*core*jar").join(File::PATH_SEPARATOR) do
	end
	FileUtils.makedirs(path_to(:target))
	wikitext.wikitext_to_xslfo :targetdir=>path_to(:target),
		  :validate => 'false',
		  :markupLanguage => 'Textile' do
	  wikitext.fileset(:dir => _('.'), :includes => "**/*.textile")
	end
      end
      Dir.glob(path_to(:target)+'/*.fo').each {
	|f|
	  dest = "#{f.sub('.fo','.pdf')}"
	    raise "File #{f} must exist " if !File.exists?(f)
	    cmd = "fop #{f} #{dest}"
	    res= system(cmd)
	  }
    end
  }
end

define('container') do
  project.group = "grp"
  project.version = '1.0.0'
  checkPreconditions
  
  define("demo", :version => "1.0.0") do
    genDoku
    compile
    package(:zip)

    check package(:zip), 'zip should contain a readme.pdf' do
      it.should contain('readme.pdf')
    end 
    
    check package(:zip), 'zip should not contain a readme.fo' do
      it.should_not contain('readme.fo')
    end 
    
    check package(:zip), 'zip should not contain a readme.textile' do
      it.should_not contain('readme.textile')
    end 
    
  end

  define("demo2", :version => "2.0.0", :base_dir=>'nested/demo2') do
    genDoku
    compile
    package(:zip)
    check package(:zip), 'zip should contain a readme.pdf' do
      it.should contain('readme.pdf')
    end 
    
    check package(:zip), 'zip should not contain a readme.fo' do
      it.should_not contain('readme.fo')
    end 
    
    check package(:zip), 'zip should not contain a readme.textile' do
      it.should_not contain('readme.textile')
    end 
    
  end
 
end
