#!/usr/bin/env ruby
# To test this file call "buildr package"
require 'buildr4osgi'
repositories.remote << "http://repo2.maven.org/maven2"
repositories.remote << "http://www.ibiblio.org/maven2"
puts repositories.local.inspect
# eclipseSDK = Buildr::artifact("org.eclipse:eclipse-SDK:zip:3.6M3-win32")
# eclipseSDK.invoke
# Buildr::unzip(File.dirname(eclipseSDK.to_s) => eclipseSDK.to_s).extract

Buildr::write "bar/src/main/java/Hello.java", "public class Hello {}"
Buildr::write "bar2/src/main/java/Hello2.java", "public class Hello2 {}"
Buildr::write "bar3/src/main/java/Hello3.java", "public class Hello3 {}"

puts repositories.remote.inspect
puts repositories.local.inspect

desc "An example Buildr4osgi project which builds a dummy p2site"

define('container') do
  project.group = "grp"
  project.version = '1.0.0'
  
  define("bar", :version => "1.0.0") do
    compile { FileUtils.makedirs _('target/root/resources') }
    package(:bundle)
    package(:sources)
  end
 
  define("foo", :version => "1.0.0") do
    f = package(:feature)
    f.plugins << project("container:bar")
    f.label = "My first feature using a p2site"
    f.provider = "Acme Inc"
    f.description = "My first feature"
    f.changesURL = "http://example.com/changes"
    f.license = "The license is too long to explain"
    f.licenseURL = "http://example.com/license"
    f.branding_plugin = "com.musal.ui"
    f.update_sites << {:url => "http://example.com/update", :name => "My dummy p2site site"}
    f.discovery_sites = [{:url => "http://example.com/update2", :name => "My dummy p2site site2"}, 
      {:url => "http://example.com/upup", :name => "My update site in case"}]
  end
  
  define("bar2", :version => "1.0.0") do
    compile { FileUtils.makedirs _('target/root/resources') }
    package(:bundle)
    package(:sources)
  end
 
  define("bar3", :version => "1.0.0") do
# With buildr 1.4.6 java and without the next line I get the following error
# Errno::ENOENT : No such file or directory - /opt/src/buildr4osgi-bug/p2site/bar3/target/root/resources
    compile { FileUtils.makedirs _('target/root/resources') }
    package(:bundle)
    package(:sources)
  end
 
  define("foo2", :version => "1.0.0") do
    f = package(:feature)
    f.plugins << project("container:bar2")
    f.plugins << project("container:bar3")
    f.label = "My second feature for a p2site"
    f.description = "My second feature"
    f.provider = "Acme Inc"
    f.description = "The best feature ever"
    f.changesURL = "http://example.com/changes"
    f.license = "The license is too long to explain"
    f.licenseURL = "http://example.com/license"
    f.branding_plugin = "com.musal.ui2"
    f.update_sites << {:url => "http://example.com/update", :name => "My dummy p2site site"}
    f.discovery_sites = [{:url => "http://example.com/update2", :name => "My dummy p2site site2"}, 
      {:url => "http://example.com/upup", :name => "My update site in case"}]
  end
  
  category = Buildr4OSGi::Category.new
  category.name = "category.id"
  category.label = "My label generated #{Time.now}"
  category.description = "The category is described here"
  category.features<< project('foo')
  category.features<< project('foo2')
  package(:site).categories << category
  package(:p2_from_site)

  check package(:p2_from_site), 'The p2site should contain a site.xml' do
    File.should exist('target/p2repository/site.xml')
  end
  check package(:p2_from_site), 'The p2site should contain an artifacts.jar' do
    File.should exist('target/p2repository/artifacts.jar')
  end
  check package(:p2_from_site), 'The p2site should contain a content.jar' do
    File.should exist('target/p2repository/content.jar')
  end
  
end
