#!/usr/bin/env ruby
# To test this file you must:
# * adapt the constant EclipseTarFile to your system! It will be expanded into an eclipse subdir.
#
# export OSGi=/path/to/existing/indigo/eclipse
# rvm jruby do buildr osgi:clean:dependencies osgi:resolve:dependencies osgi:install:dependencies
# rvm jruby do buildr buildr clean integration
#
# Tested January 2012, using
# * buildr 1.4.6 java and 
# * my patched version of buildr4osgi https://github.com/ngiger/buildr4osgi commit 0228da8fc9
# * Debian wheezy 64-bit
# * rvm 1.10.0
# * jruby 1.6.5 (ruby-1.8.7-p330) (2011-10-25 9dcd388) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_26) [linux-amd64-java]
#
# For details running PDE test for an Eclipse plugin see ../pde_tests/buildfile
# the com..example.hellorcp was created using http://www.ralfebert.de/eclipse_rcp/overview/

require 'buildr'
require 'buildr4osgi'
repositories.remote << "http://repo2.maven.org/maven2"

desc "An example buildr project which runs a PDF unit test for an Eclipse PDE project"
define('myProject') do
  project.version = '1.0.0'

  define 'com.example.hellorcp' do
  end

  define 'PhoneBookExample'  do
    PDE_test::run_pde_test(project, 'phonebookexample.dialogs.PhoneBookEntryEditorDialogTest', 
                           [ '-DmyOpt', 'aValue', '-moreopt'])
  end
  
  check file(File.join('PhoneBookExample','target','test','classes','PhoneBookExample-test_1.0.0.jar')), 'should exist' do
    it.should exist
  end
  check file(File.join('PhoneBookExample','target','test','classes','PhoneBookExample-test_1.0.0.jar')), 'should contain a manifest' do
    it.should contain(['META-INF','MANIFEST.MF'].join(File::SEPARATOR))
  end
  check file(File.join('PhoneBookExample','target','test','classes','PhoneBookExample-test_1.0.0.jar')), 'should contain the test class' do
    it.should contain(File.join('phonebookexample','dialogs','PhoneBookEntryEditorDialogTest$MyPhoneBookEntryEditorDialog.class'))
  end
  check file('TEST-PhoneBookExample.xml'), 'should exist' do
    it.should exist
  end
  check file('TEST-PhoneBookExample.xml'), 'should match success' do
    File.read('TEST-PhoneBookExample.xml').should match '<testsuite errors="0" failures="0"'
  end
  check file(File.join('reports','PDE_test','index.html')), 'should exist' do
    it.should exist
  end
end
